backend:
  name: github
  repo: luckygdesign/bibel-jcbs
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "jahr1"
    label: "Jahr 1"
    identifier_field: "Schulwoche"
    description: "Inhalte für Jahr 1"
    folder: "content/1"
    create: true
    fields:
      - { label: "Schulwoche", name: "woche", widget: "string" }
      - { label: "Bild Link", name: "image", widget: "string", required: false }
      - {
          label: "Video Link",
          name: "video",
          widget: "string",
          required: false,
        }
      - {
          label: "Challenge - Überschrift",
          name: "challengeheading",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Challenge - Text",
          name: "challengebody",
          widget: "markdown",
          required: false,
        }
      - { label: "Input - Überschrift", name: "inputheading", widget: "string" }
      - { label: "Input - Text", name: "body", widget: "markdown" }
      - { label: "Vers - Text", name: "versetext", widget: "markdown" }
      - { label: "Vers - Stellenangabe", name: "versestelle", widget: "string" }
